export const writingItems = [
  {
    title: "The Web3 Economic Stack: How Onchain Activity Creates Businesses",
    platform: "DEV Community",
    date: "September 2026",
    sortDate: "2026-09-17",
    summary:
      "Explains how onchain economic activity creates businesses beyond the blockchain itself, from trading, lending, payments, and prediction markets to wallets, data, security, and developer tools. Shows how successful primitives create adjacent markets and new ways to capture value.",
    tags: ["Web3", "Blockchain", "Startups"],
    category: "Protocols & research",
    url: "https://dev.to/lordghostx/the-web3-economic-stack-how-onchain-activity-creates-businesses-4mo6",
    featured: false,
  },
  {
    title: "Grantline: Programmable Financial Authority for AI Agents",
    platform: "Official Documentation",
    date: "August 2026",
    sortDate: "2026-08-21",
    summary:
      "Explains how signed Action Plans pass through Mandate evaluation, Preflight checks, and controller approval before Vault execution. Includes integration guides and references for delegated authority, revocation, signatures, events, and failure codes.",
    tags: ["Solidity", "AI Agents", "Financial Authority"],
    category: "Protocols & research",
    url: "https://grantline.xyz/docs",
    featured: true,
  },
  {
    title: "Convoy vs. Hookdeck vs. Svix: Picking the Right Webhook Infrastructure",
    platform: "GitHub Gist",
    date: "July 2026",
    sortDate: "2026-07-08",
    summary:
      "Compares Convoy's self-hosted gateway, Hookdeck's inbound event operations, and Svix's customer-facing webhook delivery. Examines deployment control, retries, replay, observability, pricing, and the operational trade-offs that determine which tool fits.",
    tags: ["Webhooks", "Event-Driven Architecture", "Developer Infrastructure"],
    category: "Engineering",
    url: "https://gist.github.com/LordGhostX/2ce07c5cbf5f7cf9f1d3b357c9566910",
    featured: false,
  },
  {
    title: "How to Build and Deploy a Solana Program Using Pinocchio",
    platform: "GitHub Gist",
    date: "August 2025",
    sortDate: "2025-08-07",
    summary:
      "Build a Solana counter program with Pinocchio, from account layout and manual instruction routing to validation and state updates. Covers Devnet deployment, zero-copy serialization with bytemuck, and generating a Shank IDL for client tooling.",
    tags: ["Solana", "Rust", "Blockchain Development"],
    category: "Protocols & research",
    url: "https://gist.github.com/LordGhostX/52ccaaf5752e6829b29646620d1a9ce7",
    featured: false,
  },
  {
    title:
      "Reducing Global Payment Friction with Stablecoins, Blockchains, and Solana",
    platform: "Medium",
    date: "June 2025",
    sortDate: "2025-06-06",
    summary:
      "Examines how stablecoins and Solana could improve remittances, merchant payments, and financial access. Connects settlement architecture with institutional adoption, privacy and compliance, while weighing custody risks, network limitations, and barriers to moving between fiat and crypto.",
    tags: ["Solana", "Stablecoins", "Payments"],
    category: "Protocols & research",
    url: "https://medium.com/@hrknsinst/reducing-global-payment-friction-with-stablecoins-blockchains-and-solana-edfad5e83e04",
    featured: true,
  },
  {
    title: "SIMD-0204: Building the Foundation for Slashing on Solana",
    platform: "Hashnode",
    date: "May 2025",
    sortDate: "2025-05-10",
    summary:
      "Explains how SIMD-0204 verifies and records validator violations on Solana without yet imposing financial penalties. Covers duplicate-block evidence, on-chain ProofReports, validator transparency, and the technical and governance work needed for future slashing.",
    tags: ["Solana", "Validators", "Protocol Research"],
    category: "Protocols & research",
    url: "https://lordghostx.hashnode.dev/simd-0204-building-the-foundation-for-slashing-on-solana",
    featured: false,
  },
  {
    title: "Solana at Web2 Speed: Real-Time Performance Without Fragmentation",
    platform: "Hashnode",
    date: "May 2025",
    sortDate: "2025-05-07",
    summary:
      "Explores MagicBlock's Ephemeral Rollups: temporary execution environments that accelerate delegated Solana accounts while keeping programs and assets on the base chain. Compares their composability goals with other scaling approaches and examines gaming, finance, payments, and automation use cases.",
    tags: ["Solana", "Performance", "Web3 Infrastructure"],
    category: "Protocols & research",
    url: "https://lordghostx.hashnode.dev/solana-at-web2-speed-real-time-performance-without-fragmentation",
    featured: true,
  },
  {
    title: "Starknet Improvement Proposals (SNIPs)",
    platform: "Hashnode",
    date: "April 2025",
    sortDate: "2025-04-24",
    summary:
      "Explains what Starknet Improvement Proposals contain, how they are classified, and how they move from draft through review to final status. Covers editor responsibilities, proposal guidelines, and ways to contribute feedback and participate in protocol development.",
    tags: ["Starknet", "Governance", "Protocol Research"],
    category: "Protocols & research",
    url: "https://lordghostx.hashnode.dev/starknet-improvement-proposals-snips",
    featured: false,
  },
  {
    title: "Decentralizing Starknet: Architecture, Plans, and MEV Impact",
    platform: "DEV Community",
    date: "September 2024",
    sortDate: "2024-09-11",
    summary:
      "Examines Starknet's decentralization plans through sequencer roles, Tendermint consensus, ProofChain, STRK staking, and network rewards. Discusses the coordination challenges of distributing control and how changing transaction ordering could reshape MEV opportunities and mitigation.",
    tags: ["Starknet", "MEV", "Blockchain Architecture"],
    category: "Protocols & research",
    url: "https://dev.to/lordghostx/decentralizing-starknet-architecture-plans-and-mev-impact-7ck",
    featured: true,
  },
  {
    title: "Queries to Insights: Visualizing Starknet Data with Dune",
    platform: "DEV Community",
    date: "August 2024",
    sortDate: "2024-08-09",
    summary:
      "Shows how to find Starknet queries on Dune and assemble them into dashboards for network activity, token flows, and protocol metrics. Covers visualization choices, dashboard organization, sharing, and refresh behavior so readers can interpret the data's freshness.",
    tags: ["Starknet", "Dune Analytics", "Onchain Data"],
    category: "Protocols & research",
    url: "https://dev.to/lordghostx/queries-to-insights-visualizing-starknet-data-with-dune-j8p",
    featured: false,
  },
  {
    title: "Starknet Protocols: Key Features and MEV Opportunities",
    platform: "DEV Community",
    date: "July 2024",
    sortDate: "2024-07-31",
    summary:
      "Surveys Nostra, Ekubo, zkLend, Nimbora, Vesu, and mySwap, connecting their trading and lending features to MEV opportunities. Explains arbitrage and liquidation strategies in the context of Starknet's first-come, first-served transaction ordering at publication.",
    tags: ["Starknet", "DeFi", "MEV"],
    category: "Protocols & research",
    url: "https://dev.to/lordghostx/starknet-protocols-key-features-and-mev-opportunities-574i",
    featured: false,
  },
  {
    title: "Introduction to MEV on Starknet",
    platform: "DEV Community",
    date: "July 2024",
    sortDate: "2024-07-25",
    summary:
      "Introduces Ethereum's MEV participants and tooling, then examines how Starknet's sequencing model changes the available strategies. Covers arbitrage, liquidations, cross-layer sandwich attacks, and ecosystem tools for studying and mitigating MEV.",
    tags: ["Starknet", "MEV", "Blockchain"],
    category: "Protocols & research",
    url: "https://dev.to/lordghostx/introduction-to-mev-on-starknet-1o0l",
    featured: false,
  },
  {
    title: "The state of Rust GUI libraries",
    platform: "LogRocket",
    date: "January 2024",
    sortDate: "2024-01-03",
    summary:
      "Surveys eleven Rust GUI libraries, including Tauri, Slint, iced, egui, Xilem, and Yew. Compares their approaches to building interfaces, platform support, and ecosystem trade-offs to help developers choose tools for desktop and web applications.",
    tags: ["Rust", "GUI Development", "Frontend Tooling"],
    category: "Engineering",
    url: "https://blog.logrocket.com/state-rust-gui-libraries",
    featured: false,
  },
  {
    title: "Best methods for unzipping files in Node.js",
    platform: "LogRocket",
    date: "June 2023",
    sortDate: "2023-06-02",
    summary:
      "Compares Node.js compression and archive libraries through examples using decompress, adm-zip, zlib, unzipper, and JSZip. Shows how to extract archives, create and modify ZIP contents, and unpack a ZIP buffer into a directory.",
    tags: ["Node.js", "File Handling", "JavaScript"],
    category: "Engineering",
    url: "https://blog.logrocket.com/best-methods-unzipping-files-node-js/",
    featured: false,
  },
  {
    title: "Create and manage windows in your Rust app with Winit",
    platform: "LogRocket",
    date: "May 2023",
    sortDate: "2023-05-15",
    summary:
      "Introduces Winit's window creation, event loop, and input handling through a Rust application. Shows how to configure and manage windows, respond to user events, and use Winit as a foundation for cross-platform games and graphical interfaces.",
    tags: ["Rust", "Winit", "GUI Development"],
    category: "Engineering",
    url: "https://blog.logrocket.com/create-manage-windows-rust-app-with-winit/",
    featured: false,
  },
  {
    title: "Build an application with Node.js and PouchDB",
    platform: "LogRocket",
    date: "April 2023",
    sortDate: "2023-04-19",
    summary:
      "Build a book-management API with Express and PouchDB, using LevelDB for server-side storage. Walks through database setup and routes for creating, listing, updating, and deleting book documents, including the document revisions needed for updates.",
    tags: ["Node.js", "PouchDB", "CRUD APIs"],
    category: "Engineering",
    url: "https://blog.logrocket.com/build-application-with-node-js-pouchdb/",
    featured: false,
  },
  {
    title: "How to build a blockchain with Go",
    platform: "LogRocket",
    date: "March 2023",
    sortDate: "2023-03-30",
    summary:
      "Build a small blockchain in Go to understand blocks, SHA-256 hashes, proof-of-work mining, and the genesis block. Adds transaction records and chain validation to demonstrate how linked hashes make changes to earlier blocks detectable.",
    tags: ["Golang", "Blockchain", "Backend Development"],
    category: "Protocols & research",
    url: "https://blog.logrocket.com/build-blockchain-with-go",
    featured: false,
  },
  {
    title: "Best GUI frameworks for Go",
    platform: "LogRocket",
    date: "March 2023",
    sortDate: "2023-03-10",
    summary:
      "Compares go-gtk, Qt bindings, Fyne, Walk, and Gio for building graphical applications in Go. Reviews platform coverage, widgets, rendering approaches, and dependencies, with a comparison table to help match a toolkit to a project's requirements.",
    tags: ["Golang", "GUI Development", "Frameworks"],
    category: "Engineering",
    url: "https://blog.logrocket.com/best-gui-frameworks-go/",
    featured: false,
  },
  {
    title: "Go migration guide: Node.js, Python, and Rust",
    platform: "LogRocket",
    date: "January 2023",
    sortDate: "2023-01-26",
    summary:
      "Walks through planning a migration from Python, Rust, or Node.js to Go, including language differences, dependency choices, and testing. Examines manual rewrites and available translation tools, emphasizing verification of existing behavior throughout the migration.",
    tags: ["Golang", "Migration", "Backend Development"],
    category: "Engineering",
    url: "https://blog.logrocket.com/go-migration-guide-node-js-python-rust/",
    featured: false,
  },
  {
    title: "Leverage Go workspaces for multi-module local development",
    platform: "LogRocket",
    date: "January 2023",
    sortDate: "2023-01-18",
    summary:
      "Shows how go.work and the init, use, edit, and sync commands support local development across multiple Go modules. Demonstrates using one local module from another and discusses collaboration, dependency synchronization, and release workflows.",
    tags: ["Golang", "Workspaces", "Developer Tooling"],
    category: "Engineering",
    url: "https://blog.logrocket.com/go-workspaces-multi-module-local-development/",
    featured: false,
  },
  {
    title: "Swift vs. Rust: Comparison guide",
    platform: "LogRocket",
    date: "October 2022",
    sortDate: "2022-10-27",
    summary:
      "Compares Swift and Rust through their safety models, performance goals, expressiveness, tooling, and learning curves. Discusses the strengths and limitations of each ecosystem and how they fit interface development, systems programming, and application backends.",
    tags: ["Rust", "Swift", "Programming Languages"],
    category: "Engineering",
    url: "https://blog.logrocket.com/swift-vs-rust-comparison-guide/",
    featured: false,
  },
  {
    title: "Comparing Rust and Nim",
    platform: "LogRocket",
    date: "October 2022",
    sortDate: "2022-10-07",
    summary:
      "Compares Rust's ownership model with Nim's memory-management options, syntax, and metaprogramming features. Reviews interoperability with C and C++, example programs, ecosystem limitations, and use cases spanning systems, web development, games, and developer tools.",
    tags: ["Rust", "Nim", "Programming Languages"],
    category: "Engineering",
    url: "https://blog.logrocket.com/comparing-rust-nim/",
    featured: false,
  },
  {
    title: "Integrating MongoDB into Go applications",
    platform: "LogRocket",
    date: "September 2022",
    sortDate: "2022-09-23",
    summary:
      "Connect a Go application to MongoDB using the official driver, then insert, query, update, replace, and delete documents. Covers connection checks, collection access, BSON values, and mapping database records to Go structs for easier application code.",
    tags: ["Golang", "MongoDB", "Database"],
    category: "Engineering",
    url: "https://blog.logrocket.com/integrating-mongodb-go-applications",
    featured: false,
  },
  {
    title: "Exploring Carbon, the new superset of C++",
    platform: "LogRocket",
    date: "August 2022",
    sortDate: "2022-08-26",
    summary:
      "Introduces Carbon as an experimental C++ successor, examining interoperability, generics, and proposed memory-safety improvements. Walks through installation and examples of variables, loops, functions, conditionals, and classes while discussing the language's development goals.",
    tags: ["Carbon", "C++", "Programming Languages"],
    category: "Engineering",
    url: "https://blog.logrocket.com/exploring-carbon-new-superset-c-plus-plus",
    featured: false,
  },
  {
    title: "Using CSS subgrids with container queries",
    platform: "LogRocket",
    date: "June 2022",
    sortDate: "2022-06-29",
    summary:
      "Explains how subgrid shares a parent grid's tracks and how container queries adapt components to their available space. Combines both features in an article layout, with examples of container types, naming, and responsive styling.",
    tags: ["CSS", "Responsive Design", "Frontend Development"],
    category: "Engineering",
    url: "https://blog.logrocket.com/using-css-subgrids-container-queries/",
    featured: false,
  },
  {
    title: "Comparing tools for optimizing performance in React",
    platform: "LogRocket",
    date: "June 2022",
    sortDate: "2022-06-10",
    summary:
      "Shows how the React Profiler API and DevTools reveal rendering costs, then uses React.memo to address unnecessary renders. Explains onRender metrics, flame and ranked graphs, and the trade-offs between measuring performance and applying memoization.",
    tags: ["React", "Performance", "Frontend Development"],
    category: "Engineering",
    url: "https://blog.logrocket.com/comparing-tools-optimizing-performance-react/",
    featured: false,
  },
  {
    title: "How to create a Solana wallet with Go",
    platform: "LogRocket",
    date: "October 2021",
    sortDate: "2021-10-25",
    summary:
      "Build a Solana wallet in Go using solana-go-sdk. Covers RPC connections, creating and importing accounts, checking balances, requesting development funds, and assembling, signing, and submitting SOL transfers.",
    tags: ["Golang", "Solana", "Blockchain"],
    category: "Protocols & research",
    url: "https://blog.logrocket.com/how-to-create-solana-wallet-go/",
    featured: false,
  },
  {
    title: "Documenting Go web APIs with Swag",
    platform: "LogRocket",
    date: "October 2021",
    sortDate: "2021-10-04",
    summary:
      "Build a todo API with Gin, then generate Swagger documentation from Go annotations using Swag. Covers describing routes, parameters, and responses, generating the documentation files, and serving an interactive Swagger UI alongside the API.",
    tags: ["Golang", "API Documentation", "Swagger"],
    category: "Engineering",
    url: "https://blog.logrocket.com/documenting-go-web-apis-with-swag/",
    featured: false,
  },
  {
    title: "Build and deploy a web app with Python, Flask, and Doppler",
    platform: "DEV Community",
    date: "October 2021",
    sortDate: "2021-10-04",
    summary:
      "Configure Doppler projects and secrets, inject them into a Flask process with the CLI, and read them as environment variables in Python. Extends the setup to Heroku so the deployed application receives its configuration through Doppler's integration.",
    tags: ["Python", "Flask", "Secrets Management"],
    category: "Security",
    url: "https://dev.to/lordghostx/build-and-deploy-a-web-app-with-python-flask-and-doppler-9jm",
    featured: false,
  },
  {
    title: "A comprehensive guide to data structures in Go",
    platform: "LogRocket",
    date: "September 2021",
    sortDate: "2021-09-07",
    summary:
      "Explains Go arrays, slices, maps, and structs through working examples of initialization, access, updates, and nesting. Covers slice length and capacity, map key checks and deletion, and struct methods with pointer receivers for updating state.",
    tags: ["Golang", "Data Structures", "Programming Fundamentals"],
    category: "Engineering",
    url: "https://blog.logrocket.com/comprehensive-guide-data-structures-go/",
    featured: false,
  },
  {
    title: "Build a profanity filter API with GraphQL",
    platform: "LogRocket",
    date: "August 2021",
    sortDate: "2021-08-05",
    summary:
      "Starts with a word-list profanity detector, demonstrates its limitations, and improves filtering with Python's better-profanity library. Exposes detection and censored text through a Flask GraphQL API, with schemas and queries tested in GraphiQL.",
    tags: ["Python", "GraphQL", "API Development"],
    category: "Engineering",
    url: "https://blog.logrocket.com/build-profanity-filter-api-graphql/",
    featured: false,
  },
  {
    title: "Implementing User Authentication in a Python Application",
    platform: "LoginRadius",
    date: "July 2021",
    sortDate: "2021-07-07",
    summary:
      "Integrates LoginRadius with Flask using its Python SDK and hosted authentication pages. Covers API credentials, domain allowlisting, registration and login redirects, retrieving user profiles from access tokens, and invalidating tokens on logout.",
    tags: ["Python", "Authentication", "Flask"],
    category: "Security",
    url: "https://www.loginradius.com/blog/engineering/guest-post/user-authentication-in-python",
    featured: false,
  },
  {
    title: "Building a Contact Manager with Python, Flask, and HarperDB",
    platform: "DEV Community",
    date: "June 2021",
    sortDate: "2021-06-02",
    summary:
      "Connect a Flask and Bootstrap contact manager to HarperDB through its Python SDK. Sets up a cloud database, schema, and table, then implements contact creation, search, updates, and deletion using HarperDB's query operations.",
    tags: ["Python", "Flask", "HarperDB"],
    category: "Engineering",
    url: "https://dev.to/lordghostx/building-a-contact-manager-with-python-flask-and-harperdb-1h53",
    featured: false,
  },
  {
    title:
      "Implementing Two-factor Authentication with Flask, PyOTP, and Fauna",
    platform: "DEV Community",
    date: "April 2021",
    sortDate: "2021-04-23",
    summary:
      "Builds a Flask registration and login flow with Fauna, then adds time-based one-time passwords using PyOTP. Walks through authenticator enrollment, secret provisioning, code verification, and restricting protected routes until both authentication steps succeed.",
    tags: ["Python", "Two-Factor Authentication", "Fauna"],
    category: "Security",
    url: "https://dev.to/lordghostx/implementing-two-factor-authentication-with-flask-pyotp-and-fauna-4jf3",
    featured: false,
  },
  {
    title:
      "How To Implement Biometric 2FA in a Cryptocurrency Wallet with Python, Flask and TypingDNA",
    platform: "DEV Community",
    date: "April 2021",
    sortDate: "2021-04-16",
    summary:
      "Adds typing-pattern authentication to a Flask cryptocurrency wallet with TypingDNA. Covers recording and enrolling users, verifying login attempts, an email-OTP fallback, and requiring an additional identity check before wallet withdrawals.",
    tags: ["Python", "Biometric Authentication", "Security"],
    category: "Security",
    url: "https://dev.to/typingdna/how-to-implement-biometric-2fa-in-a-cryptocurrency-wallet-with-flask-and-typingdna-3o41",
    featured: false,
  },
  {
    title: "Managing User Authentication and Sessions with Fauna and Flask",
    platform: "DEV Community",
    date: "March 2021",
    sortDate: "2021-03-25",
    summary:
      "Integrates Fauna's identity and session features into a Flask application. Covers user creation, password authentication, validating session tokens, retrieving the current user's profile, logging out, and changing passwords, alongside the distinction between authentication and authorization.",
    tags: ["Python", "Authentication", "Fauna"],
    category: "Security",
    url: "https://dev.to/lordghostx/managing-user-authentication-and-sessions-with-fauna-and-flask-5h5h",
    featured: false,
  },
  {
    title: "Building Faunabin: A Pastebin Clone with Python and Fauna",
    platform: "DEV Community",
    date: "January 2021",
    sortDate: "2021-01-19",
    summary:
      "Build Faunabin, a Pastebin-style app with Flask, Bootstrap, and Fauna. Creates forms for submitting text, stores pastes under unique identifiers, serves shareable result pages, and deploys the application to Heroku with Gunicorn.",
    tags: ["Python", "Flask", "Fauna"],
    category: "Engineering",
    url: "https://dev.to/lordghostx/building-faunabin-a-pastebin-clone-with-python-and-fauna-436b",
    featured: false,
  },
  {
    title: "How to Host Flask Applications on Namecheap cPanel",
    platform: "DEV Community",
    date: "December 2020",
    sortDate: "2020-12-27",
    summary:
      "Deploy a Flask application through Namecheap's cPanel Python App interface. Covers selecting the runtime and domain, uploading project files, configuring passenger_wsgi.py, installing requirements, and restarting the application to apply changes.",
    tags: ["Python", "Flask", "Deployment"],
    category: "Engineering",
    url: "https://dev.to/lordghostx/how-to-host-flask-applications-on-namecheap-cpanel-299b",
    featured: false,
  },
  {
    title: "A Friendly Introduction to Cybersecurity",
    platform: "DEV Community",
    date: "December 2020",
    sortDate: "2020-12-22",
    summary:
      "Introduces common cyberattacks, their impact, and the different roles within security. Explains offensive and defensive teams, the stages of a penetration test, and learning paths and certifications for people exploring the field.",
    tags: ["Cybersecurity", "Security", "Programming Fundamentals"],
    category: "Security",
    url: "https://dev.to/lordghostx/a-friendly-introduction-to-cybersecurity-1e3a",
    featured: false,
  },
  {
    title: "The Zen of Python; An In-depth Explanation",
    platform: "DEV Community",
    date: "December 2020",
    sortDate: "2020-12-22",
    summary:
      "Unpacks each of Tim Peters' Zen of Python principles with explanations and code examples. Connects readability, explicit behavior, simple structure, error handling, and namespaces to everyday decisions about writing and organizing Python programs.",
    tags: ["Python", "Programming Fundamentals", "Code Quality"],
    category: "Engineering",
    url: "https://dev.to/lordghostx/the-zen-of-python-an-in-depth-explanation-45fm",
    featured: false,
  },
  {
    title: "Build and Deploy a Serverless URL Shortener with Python and Fauna",
    platform: "DEV Community",
    date: "December 2020",
    sortDate: "2020-12-17",
    summary:
      "Build a Flask URL-shortening API backed by Fauna, generating short identifiers and storing their original destinations. Implements link creation and redirects, then packages the application with Gunicorn and deploys it to Heroku.",
    tags: ["Python", "Serverless", "Fauna"],
    category: "Engineering",
    url: "https://dev.to/lordghostx/build-and-deploy-a-serverless-url-shortener-with-python-and-fauna-3077",
    featured: false,
  },
  {
    title: "Building a Telegram Bot with Python and Fauna",
    platform: "DEV Community",
    date: "December 2020",
    sortDate: "2020-12-01",
    summary:
      "Create a Telegram todo bot with Python, BotFather, and Fauna. Sets up collections and indexes, connects bot commands to database queries, and lets users add tasks, list them, toggle completion, and delete them.",
    tags: ["Python", "Telegram Bot", "Fauna"],
    category: "Engineering",
    url: "https://dev.to/lordghostx/building-a-telegram-bot-with-python-and-fauna-494i",
    featured: false,
  },
  {
    title:
      "Building a QR Code Identity System with Fernet Symmetric Encryption Algorithm in Python",
    platform: "DEV Community",
    date: "April 2020",
    sortDate: "2020-04-01",
    summary:
      "Build a student ID prototype that generates and reads QR codes in Python. Uses Fernet to encrypt student identifiers before encoding them, then decrypts scanned values to look up records and reject altered identifiers.",
    tags: ["Python", "Encryption", "Cybersecurity"],
    category: "Security",
    url: "https://dev.to/lordghostx/building-a-qr-code-identity-system-with-fernet-symmetric-encryption-algorithm-in-python-2ffd",
    featured: false,
  },
];
